-- Bellwether — 003 M1: sampling frame, tag normalisation, retention decoupling
--
-- Everything here is idempotent; bellwether.migrate re-runs every file.
--
-- Phase 1 of two. This file ADDS tag_ids and keeps the original tags column,
-- so a pipeline still running the previous code cannot write rows the new
-- schema silently loses. The drop of tags happens in a later migration, after
-- the deployed pipeline is known to be writing both. Doing it in one step
-- would open a window where the two disagree, and the symptom would be missing
-- labels rather than an error.

-- ---------------------------------------------------------------------------
-- Tag dimension
--
-- 67 distinct tags exist across the whole feed (measured 2026-08-13). Storing
-- them as text on every row costs ~40 bytes; storing smallint ids costs ~10,
-- and the GIN index shrinks with the payload. That is most of the 372 -> ~300
-- bytes per row that M1 §4 needs.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS landing.tag_names (
    tag_id    smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name  text NOT NULL UNIQUE,
    first_seen_utc timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE landing.rc_events
    ADD COLUMN IF NOT EXISTS tag_ids smallint[];

-- Sampling weight is now the inverse sampling probability rather than 1.0.
-- Existing rows keep 1.0 and remain correct: M0 ingested a census, and the
-- weight for a census IS 1.0. That is precisely why the column is written at
-- observation time (M1-FR-2) — weighted estimates stay valid across the change
-- of frame instead of needing reconstruction from a rule that has since moved.
ALTER TABLE landing.rc_events
    ADD COLUMN IF NOT EXISTS in_maturity_cohort boolean NOT NULL DEFAULT false;


-- ---------------------------------------------------------------------------
-- Backfill tag ids for rows written before this migration
-- ---------------------------------------------------------------------------
INSERT INTO landing.tag_names (tag_name)
SELECT DISTINCT t
  FROM landing.rc_events, unnest(tags) AS t
ON CONFLICT (tag_name) DO NOTHING;

UPDATE landing.rc_events e
   SET tag_ids = COALESCE(
       (SELECT array_agg(n.tag_id ORDER BY n.tag_id)
          FROM unnest(e.tags) AS t
          JOIN landing.tag_names n ON n.tag_name = t),
       '{}'::smallint[])
 WHERE e.tag_ids IS NULL;


-- ---------------------------------------------------------------------------
-- Indexes (M1-FR-5)
--
-- rc_events_event_ts_revid_idx is redundant: every query that used it filters
-- on event_ts and then reaches rows by primary key, which the plain event_ts
-- index plus the PK already serve. It cost ~25 bytes a row to duplicate an
-- access path that existed.
-- ---------------------------------------------------------------------------
DROP INDEX IF EXISTS landing.rc_events_event_ts_revid_idx;

CREATE INDEX IF NOT EXISTS rc_events_tag_ids_gin_idx
    ON landing.rc_events USING gin (tag_ids);

-- Supports the labelling queue, which selects by age among events not yet
-- checked, and now also splits on cohort membership.
CREATE INDEX IF NOT EXISTS rc_events_cohort_event_ts_idx
    ON landing.rc_events (in_maturity_cohort, event_ts);


-- ---------------------------------------------------------------------------
-- Decouple evidence retention from raw retention (M1-FR-10)
--
-- rc_events ages out at 30 days; labels are sealed and kept for 90, and cohort
-- label_checks for 180. A foreign key would chain the longer retention to the
-- shorter one and force the evidence out with the raw material.
--
-- revid is MediaWiki's own immutable identifier. It is meaningful without a
-- local row to point at, which is what makes dropping the constraint safe
-- rather than merely convenient.
-- ---------------------------------------------------------------------------
ALTER TABLE outcome.labels       DROP CONSTRAINT IF EXISTS labels_revid_fkey;
ALTER TABLE outcome.label_checks DROP CONSTRAINT IF EXISTS label_checks_revid_fkey;


-- ---------------------------------------------------------------------------
-- Grants for the new table
--
-- ALTER DEFAULT PRIVILEGES in 002 covers tables created AFTER it ran, and this
-- file may be applied to a database where it already has. Granting explicitly
-- costs nothing and removes the ordering dependency.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT ON landing.tag_names TO bellwether_writer;
GRANT SELECT          ON landing.tag_names TO bellwether_readonly;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA landing TO bellwether_writer;
